# Jekyll configuration for GitHub Pages
title: World of Darkness Hub by ParadoxGirl
description: A comprehensive website hub for World of Darkness tools and resources
url: "https://srparadox.github.io"
baseurl: "/WoD-Creator"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .github/
  - downloads/README.md
  - tools/README.md

# Include files that start with underscores
include:
  - _pages

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Default layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Custom variables
author: ParadoxGirl
social:
  github: SRparadox

# SEO settings
logo: /assets/images/logo.png
social:
  name: World of Darkness Hub by ParadoxGirl
  links:
    - https://github.com/SRparadox/WoD-Creator
